/**
 * CLI help text.
 */

/** Print the help text to stderr (or wherever `out` points). */
export function formatHelp(version: string): string {
  return [
    `envoy-harness ${version}`,
    "",
    "Usage:",
    "  envoy-harness [flags] [prompt]",
    "  envoy-harness [flags] -                    # read prompt from stdin",
    "  envoy-harness [flags] <prompt-file>        # read prompt from a file",
    "  envoy-harness self-evolve [flags]          # run one self-evolution cycle",
    "  envoy-harness doctor [--config <path>]     # health checks",
    "  envoy-harness tui [flags]                  # terminal UI (envoy-harness-tui)",
    "  envoy-harness web [flags]                  # browser UI (envoy-harness-web)",
    "",
    "Flags (run):",
    "  --sandbox <mode>       read-only | workspace-write | danger-full-access",
    "  --sandbox-executor <b> landlock | seatbelt | windows-sandbox | none  (opt-in kernel sandbox; default none)",
    "  --approval <mode>      unless-trusted | on-request | granular | never",
    "  --model <id>           LLM model identifier",
    "  --provider <name>      LLM provider (openai, anthropic, deepseek, ollama, …)",
    "  --base-url <url>       override provider API base (OpenAI-/Anthropic-compatible)",
    "  --cwd <path>           override working directory",
    "  --max-turns <n>        agent loop iteration cap (default 50 one-shot / 200 REPL)",
    "  --max-cost-usd <n>     cost ceiling (default 5.00 one-shot; uncapped REPL)",
    "  --resume <session-id>  resume a previous session",
    "  --resume-remote <node>/<session>  resume from a mesh peer (requires mesh adapter)",
    "  --fork <session-id>    fork a previous session",
    "  --persist              persist this session to disk (REPL auto-persists on TTY)",
    "  --no-subagents         disable default local task / LocalMeshSubmitter (R8)",
    "  --session-dir <path>   session storage dir (default ~/.local/state/envoy-harness/sessions)",
    "  --config <path>        TOML config file (default ~/.config/envoy-harness/config.toml)",
    "  --import-config <path> import a foreign config file (use with --from <format>)",
    "  --from <format>        source format for --import-config (v0: codex)",
    "  --plugin <name>        load a plugin (repeatable; must be in the curated whitelist)",
    "  --plugin-config <spec> per-plugin config (repeatable; '<name>.<key>=<value>')",
    "  --peers <id>@<host:port>  mesh peer endpoint (repeatable; also ENVOY_PEERS)",
    "  --discovery <mode>        peer discovery: static|mdns|none (default static)",
    "  --connect-timeout-ms <n>  per-peer TCP connect timeout",
    "  --connect-timeout-ms <n>  per-peer connect timeout (default 10000)",
    "  --plan                 read + plan only, no writes",
    "  --repl                 interactive REPL (no positional prompt)",
    "  --acp                  serve ACP JSON-RPC on stdio (hosts / TUI)",
    "  --json                 JSON Lines output (machine-readable)",
    "  --quiet                suppress human output",
    "  --no-color             disable ANSI colors",
    "  --verbose              print hook fires and validator verdicts",
    "  --help                 print this help and exit",
    "  --version              print version and exit",
    "",
    "Flags (self-evolve):",
    "  --scoreboard <path>    scoreboard YAML file",
    "  --snapshot-dir <path>  snapshot directory",
    "  --benchmark <path>     frozen benchmark YAML file",
    "  --ruleset <path>       live ruleset file (committed on kept)",
    "  --agents-md <path>     user AGENTS.md (snapshotted)",
    "  --adoptions <path>     federated adoptions YAML file",
    "  --commit               actually write the candidate (default: shadow)",
    "  --recent-failures <n>  recent entries to feed the prompt (default 20)",
    "  --pull                 opt in to federated pull (default: off)",
    "  --peer-id <id>         this peer's id (recorded in adoptions log)",
    "",
    "Flags (tui):",
    "  --spawn                spawn envoy-harness --acp (default for envoy-harness tui)",
    "  --demo                 in-process demo backend",
    "  --cluster-only         mesh cluster console",
    "  --peers <id>@<host:port>  static peer (repeatable)",
    "  --connect-timeout-ms <n>",
    "  --provider <name>      LLM provider for --spawn",
    "  --model <id>           LLM model for --spawn",
    "  --base-url <url>       override provider API base for --spawn",
    "  --ask-permission       demo permission prompts",
    "  --no-color             disable ANSI colors",
    "",
    "Flags (web):",
    "  --port <n> / --host <addr> / --cwd <path>",
    "  --provider <name> / --model <id> / --base-url <url> / --persist / --no-subagents",
    "  --peers <id>@<host:port> / --dev / --no-open",
    "",
    "See docs/design.md §19 for the full surface.",
  ].join("\n");
}
